version: '3.4'

networks:
    bookybook-pro:

services:
    db-pro: 
        image: mcr.microsoft.com/mssql/server:2019-CU21-ubuntu-20.04
        restart: always 
        ports:
            - 0977:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=<YourStrong@Passw0rd>
        networks:
            - bookybook-pro 
        volumes:
            - db-data-pro:/var/opt/mssql
        healthcheck:
            test: ["CMD", "sqlcmd", "-U", "sa", "-P", "<YourStrong@Passw0rd>", "-Q", "SELECT 1"]
            interval: 30s
            timeout: 10s
            retries: 3

    api-pro:
        restart: unless-stopped 
        ports:
            - 7790:80
        build: 
          context: .
          dockerfile: Dockerfile
        depends_on:
            - db-pro
        networks:
            - bookybook-pro
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        volumes:
            - logs-pro:/app/Logs

    web-pro:
        image: icbmasterchief/bookybook-web-pro
        restart: unless-stopped
        ports:
            - 8080:80
        depends_on:
            - api-pro
        networks:
            - bookybook-pro

volumes:
    db-data-pro: {}
    logs-pro:
      driver: local 
      driver_opts:
        type: none
        device: ./Logs
        o: bind

