version: '3.4'
 
networks:
    bookybook:

services:
    db: 
        image: mcr.microsoft.com/mssql/server:2019-CU21-ubuntu-20.04
        restart: always 
        ports:
            - 0977:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=<YourStrong@Passw0rd>
        networks:
            - bookybook 
        volumes:
            - db-data:/var/opt/mssql
        healthcheck:
            test: ["CMD", "sqlcmd", "-U", "sa", "-P", "<YourStrong@Passw0rd>", "-Q", "SELECT 1"]
            interval: 30s
            timeout: 10s
            retries: 3

    api:
        restart: unless-stopped 
        ports:
            - 7790:80 
        build: 
          context: .
          dockerfile: Dockerfile
        depends_on:
            - db
        networks:
            - bookybook


    # api:
    #     #container_name: apiContainer
    #     #image: apidb-dockerdemo:1.2
    #     ports:
    #         - 7790:80   #never change internal port!!!
    #     networks:
    #         - backend
    #     build:
    #       context: .
    #       dockerfile: BookyBook.API/Dockerfile
    #     depends_on:
    #         - db    #API without db running is useless

   # web:
        #container_name: webContainer
   #     image: web:1.0
    #    ports:
     #       - 9000:8080 
      #  depends_on:
       #     - api

volumes:
    db-data: {}